# Generated by Django 2.1.1 on 2018-11-28 00:12

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(choices=[('GYM', 'Weightlifting'), ('DNC', 'Dancing'), ('SKI', 'Skiing'), ('FLM', 'Film'), ('KRF', 'Korfball'), ('SWM', 'Swimming'), ('PHT', 'Photography'), ('TNS', 'Tennis'), ('CHESS', 'Chess'), ('Debating', 'Debating')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('dateOfBirth', models.DateField(default='YYYY-MM-DD', max_length=8)),
                ('gender', models.CharField(max_length=7, null=True)),
                ('profileImage', models.ImageField(default=None, upload_to='profile_images')),
                ('following', models.ManyToManyField(blank=True, to='thunderapp.Member')),
                ('hobbies', models.ManyToManyField(to='thunderapp.Hobby')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4096)),
                ('public', models.BooleanField(default=True)),
                ('time', models.DateTimeField()),
                ('recip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to='thunderapp.Member')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='thunderapp.Member')),
            ],
        ),
    ]
