# Generated by Django 2.1.1 on 2018-12-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thunderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('GENDER', 'OTHER')], max_length=7, null=True),
        ),
    ]
