# Generated by Django 2.1.4 on 2018-12-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thunderapp', '0002_auto_20181201_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='thunderapp.Message', to='thunderapp.Member'),
        ),
    ]
